# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eed0a9f8573c65a30416eb0901bf31c395b88ea3915e84a154c165bd2f83cf84e07792e4eb649a8074ce25a4862c1c44c67e23688ef354e320d41bbffad856f

test:
  secret_key_base: f0a6d479298c9ce4e23a5aedf2d72459f9dcf0077481afeb8fecc52843cb634f133f5b9caf86cd69794f82e5628cc8e66d93d9f25351a6baf32206b2b5bbc621

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
